keys:
  - &host_flores age1c9pehf9923ujjv4py0vrz0azgz6e9weucw754wmk6xnel5mr4dzqvfv32z
  - &host_papua_0 age1waqyjjtrld7cyyndmvk9aduh97dd5c979fzgtr0edhq7a5l93u4staxuqk
  - &user_dave age1wlg4ft6vdy57w5xysgr05xdrkw4c42j8gzv5tglswldes5g3js3q4chq2j
  - &user_ireen age1pz0ukt9fr4mujcsapxkzeyajfaw78p95qntk28u4nsdefza98a7ss06hv4
  - &user_root age1vm8qg9zqqc50km9e7mja2ys2sghl76pxseu64qrly0t3uu060g8sj43r46
  - &user_bootstrap age1aze8me5qy3v56pc2a3dan682zlssesh9tau3scjt4wf3sajjf9gsj0dnzs
creation_rules:
  - path_regex: hosts/common/secrets/.*
    key_groups:
      - age:
          - *host_flores
          - *user_dave
          - *user_ireen
          - *user_root
          - *user_bootstrap
          - *host_papua_0
  - path_regex: users/secrets.yaml
    key_groups:
      - age:
          - *host_flores
          - *user_dave
          - *user_root
          - *user_bootstrap
          - *host_papua_0
  - path_regex: hosts/flores/secrets/.*
    key_groups:
      - age:
          - *host_flores
          - *user_ireen
          - *user_root
          - *user_bootstrap
          - *host_papua_0
